-- +goose Up

-- chat_sessions.coverage_last_classified_seq lets the post-turn classifier
-- short-circuit when there's no new user content since it last ran. The
-- handler stores the max chat_messages.seq it classified through; on the
-- next assistant turn, if the new max user-msg seq is <= this value, we
-- skip the LLM call entirely and reuse the persisted covered set.
--
-- Default 0 = "never classified" (every seq is > 0 in practice since
-- chat_messages.seq is generated by a per-session counter starting at 1).
ALTER TABLE chat_sessions
    ADD COLUMN coverage_last_classified_seq integer NOT NULL DEFAULT 0;

-- +goose Down

ALTER TABLE chat_sessions DROP COLUMN IF EXISTS coverage_last_classified_seq;
